### PR TITLE
Updated tutorials page and added new tutorial video (running dog demo)

### PR DESCRIPTION
**Pull request by melvinlu**

### CODE REVIEW

**Comment by brollb** [comment]
Overall, looks good. A couple things:
- the rounded edges of the top grey bar are messed up on the tutorial pages (they are no longer rounded)
- The header background for the videos looks a little rough. The contrast of black on white is a little harsh and the sharp corners don't help. I would either check out some bootstrap component to replace it (such as a panel to nest the videos in) or remove them entirely

**Comment by melvinlu** [comment]
@brollb Good eyes! Take a look now.

**Comment by melvinlu** [comment]
It does look better with no headers!

**Comment by brollb** [comment]
looks good! thanks!

**Pull request merged**
