### PR TITLE
add roccem page

### PR DESCRIPTION
**Pull request by samankittani**
This PR adds a roccem curriculum page and a navbar link

### CODE REVIEW

**Comment by dragazo** [comment]
Only thing i'm not sure about is if the `/ROCCEM` link will work since it's served as `/roccem` (idk if it:s case sensitive)

**Comment by dragazo** [comment]
Only thing i'm not sure about is if the `/ROCCEM` link will work since it's served as `/roccem` (idk if it:s case sensitive).

Oh also, is this another curriculum thing? If so we can remove the navbar entry and just add it somewhere on the curriculum page (order doesn't matter).

**Comment by samankittani** [comment]
thanks for the feedback! The route was case insensitive. I removed the entry from the navbar and added an entry in the curriculum page

**Comment by samankittani** [comment]
I will go ahead and merge if this looks good to you

**Comment by samankittani** [comment]
Thanks for updating the deployment!

**Pull request merged**
